CREATE TABLE IF NOT EXISTS `proveedores` (
  `id`         INT          NOT NULL AUTO_INCREMENT,
  `nombre`     VARCHAR(150) NOT NULL,
  `telefono`   VARCHAR(30)  DEFAULT NULL,
  `email`      VARCHAR(150) DEFAULT NULL,
  `direccion`  VARCHAR(200) DEFAULT NULL,
  `activo`     TINYINT(1)   NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP    NULL     DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP    NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
